### ISSUE TITLE
Enforce variable allocation before other instructions

### ISSUE THREAD

**Issue by BenjaminSchaaf** [pektin/jam#52]
Currently, if a variable is first used inside a loop it will get allocated every iteration. Allocation should happen before any loops.

**Comment by CameronLonsdale** [comment]
Causes segfaults in lli

**Comment by BenjaminSchaaf** [comment]
Tested by: https://github.com/pektin/jam/blob/master/compiler/tests/language_features/branching_error.jm

**Comment by BenjaminSchaaf** [comment]
Fixed as of c131fffa6d573fbf3d5566eea8f760adf30a571c
