### ISSUE TITLE
Segfaulting with classes

### ISSUE THREAD

**Issue by CameronLonsdale** [pektin/jam#66]
```
#0,1,2\n

class Vector3D
  x:Real
  y:Real
  z:Real

  new(a:Real, b:Real, c:Real)
    x = a
    y = b
    z = c
  end

  def print()
    puts(x)
    puts(",")
    puts(y)
    puts(",")
    puts(z)
  end

  def self + other:Vector3D
    x = x + other.x
    y = y + other.y
    z = z + other.z
  end

  def self - other:Vector3D
    x = x - other.x
    y = y - other.y
    z = z - other.z
  end

  def self * other:Vector3D
    return x*other.x + y*other.y + z*other.z
  end

  def cross(other:Vector3D)
    a = y*other.z - z*other.y
    b = x*other.z - z*other.x
    c = x*other.y - y*other.x
    n = Vector3D(a,b,c)
    return n
  end
end

vect = Vector3D(3.0, 2.0, 1.0)
vect2 = Vector3D(5.0, 4.0, 2.0)
n = vect.cross(vect2)
n.print()
```
The error seems to happen with the line/s
vect = Vector3D(3.0, 2.0, 1.0)

it was originally z = Vector3D(3.0, 2.0, 1.0). And that produced the ambiguity error. Changing z to another name, like vect, causes a segmentation fault

**Comment by BenjaminSchaaf** [comment]
The segfault happens with the presence of `n = Vector3D(a,b,c)` inside the `cross` method.

**Comment by BenjaminSchaaf** [comment]
Doing: `Vector3D(3.0, 2.0, 1.0).cross(Vector3D(5.0, 4.0, 2.0))` instead of storing each vector in a separate variable negates the segmentation fault and gives the desired outcome.

**Comment by BenjaminSchaaf** [comment]
Test was added with 25c99a19509fd3a3aba5825f1ee3eaa38cffc4fd. Test passed with 6708ea5b3348a1782f9b26f039fb8c17d54fada5.
